name: Android APK Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build SMSIndia Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4️⃣ Make Gradle wrapper executable
      - name: Grant Gradle Permissions
        run: chmod +x ./gradlew

      # 5️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          target: default
          cache: true

      # 6️⃣ Ensure google-services.json exists
      - name: Verify Firebase Config
        run: |
          if [ ! -f app/google-services.json ]; then
            echo "::warning::⚠️ Missing google-services.json in app/ directory!"
          else
            echo "✅ google-services.json found!"
          fi

      # 7️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 8️⃣ Rename output APK for clarity
      - name: Rename APK
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          VERSION_NAME=$(grep versionName app/build.gradle | sed -E 's/.*"([0-9.]+)".*/\1/')
          NEW_NAME="SMSIndia-v${VERSION_NAME}-debug.apk"
          mv "$APK_PATH" "app/build/outputs/apk/debug/${NEW_NAME}"
          echo "✅ Renamed to ${NEW_NAME}"

      # 9️⃣ Upload the renamed APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMSIndia-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
